spring.application.name=dge-api-paef-v1
server.servlet.context-path=/api
server.port=8880
api.version=1.0

# BD principal (db_paef)
spring.datasource.url=jdbc:postgresql://localhost:5432/db_paef_igrp?currentSchema=paef
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

### FLYWAY CONFIGURATIONS
spring.flyway.enabled=false
spring.flyway.schemas=public
spring.flyway.locations=classpath:db/migration

### OTHERS CONFIGURATIONS
spring.jackson.property-naming-strategy=SNAKE_CASE
link.page.igrp=http://localhost:9080/paef/app/webapps?r=paef/$page$/index&dad=paef&target=_blank&isPublic=1&lang=pt_PT
link.page.document_viewer=https://app-paef.gov.cv/paef/app/webapps?r=igrp/File/get-file&dad=paef&target=_blank&uuid=

###DUC LIKNS
duc.estado-url=https://gateway-pdex.gov.cv/t/financas.gov/mfcreateducprod/1.0.0/postProcessBancaEstadoDUC
duc.report-base-url=https://portalrep.gov.cv/reports/rwservlet?SIGOF_DUC
duc.ver_duc=https://coremf.gov.cv/report/r/sigof_duc?&p_nu_duc=
duc.pagar_duc=https://mf.gov.cv/web/mf/pagamento-duc?entidade=$entidade$&referencia=$referencia$&montante=$montante$&call_back_url=https://igrp.paef.devtrust.cv/paef/rest/feedback/pagamento
authorization.integration.duc=Bearer eyJ4NXQiOiJNekUyTmpJeE9UUXdPR05tWlRFd05qa3pZbUZoT1dFMU5EVXhNREJtWkdOak1tVXdOV0kwWkRFMVlqWXhOVFkwTW1FeU1UbGhZekJtTUdFM1lqUmlNdyIsImtpZCI6Ik16RTJOakl4T1RRd09HTm1aVEV3TmprelltRmhPV0UxTkRVeE1EQm1aR05qTW1Vd05XSTBaREUxWWpZeE5UWTBNbUV5TVRsaFl6Qm1NR0UzWWpSaU13X1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJvZGFpci5mb3J0ZXNAbWYuZ292LmN2QGZpbmFuY2FzLmdvdiIsImF1dCI6IkFQUExJQ0FUSU9OIiwiYXVkIjoiazdQSzRYRk9iWk1WYTFWbjM2YWhMamVJVWdZYSIsIm5iZiI6MTczMzQ5ODQxOCwiYXpwIjoiazdQSzRYRk9iWk1WYTFWbjM2YWhMamVJVWdZYSIsInNjb3BlIjoiZGVmYXVsdCIsImlzcyI6Imh0dHBzOlwvXC9sb2NhbGhvc3Q6OTQ0M1wvb2F1dGgyXC90b2tlbiIsImV4cCI6OTIyMzM3MjAzNjg1NDc3NSwiaWF0IjoxNzMzNDk4NDE4LCJqdGkiOiIxYzYxYWZlYi01OGQ0LTQ5ZjAtYWFjMy1kNmQ1ODgxMDBiYjkifQ.HlfShQasdN3Fo5L8Nmub7ky9fAzmch0TUw6Tx_taptgoc6W7XP-n3qsUKygyQstqAR3ilEAqNqboB8WZL8OE0SDyEj8Bb_PK1kHEAsxIdshteacmisa9y6CthGHhzhy6uo1F12IDZ0WFb2sFEzjrtGN5KyiGRQfzhSBrXI9j_IzQ-4qgvNJtyhnCFmkUba-IsnpVmqh55DTkqUIDobewfL1e9WD5YQvkPhJF8Nr5g5cXes-pwXi3mnRqNx2XidZ3vVhk_TVF-iHpKgx_lvsMQF6JtLJT0ndrL9smUvwoUawij8Z1tRCYeN1NKqM4M2ZNlmZDye5-zQTU8NM0WsRzmw
